apiVersion: v1
kind: Service
metadata:
 labels:
   name: nginx
 name: nginx
spec:
 ports:
   - port: 80
 selector:
   app: nginx
 type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deploy
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
        run: nginx
        tier: web
    spec:
      containers:
      - image: nginx
        name: nginx